export * from './components/Checkout'
export { default as UnconfirmedCheckout } from './components/checkout/UnconfirmedCheckout'
export { default as PendingPaymentCheckout } from './components/checkout/PendingPaymentCheckout'
export { default as PaymentReceivedCheckout } from './components/checkout/PaymentReceivedCheckout'
export { default as ExpiredCheckout } from './components/checkout/ExpiredCheckout'
export * from './hooks/useCheckout'
export * from './hooks/useCheckoutSuccess'
export * from './hooks/useProducts'
export * from './hooks/useCustomer'
export type { CustomerData, UseCustomerOptions } from './hooks/useCustomer'
export * from './providers'
export type { MdkError, Result } from './types'
export { failure, success } from './types'
// Re-export GetCustomerInput as CustomerIdentifier for backwards compatibility
export type { GetCustomerInput as CustomerIdentifier } from '@moneydevkit/api-contract'
