name: Prepare demo app
description: Install root deps, build packages, pack local tarballs, sync lockfile, and install demo deps.
inputs:
  demo-dir:
    description: Relative path to the demo app directory
    default: examples/mdk-nextjs-demo
runs:
  using: composite
  steps:
    - name: Install root dependencies
      shell: bash
      run: npm ci

    - name: Build @moneydevkit/core
      shell: bash
      run: npm run build --workspace packages/core

    - name: Pack @moneydevkit/core tarball
      shell: bash
      run: |
        DEMO_DIR="${{ inputs.demo-dir }}"
        rm -f "$DEMO_DIR/moneydevkit-core-local.tgz"
        npm pack ./packages/core --pack-destination "$DEMO_DIR"
        mv "$DEMO_DIR"/moneydevkit-core-*.tgz "$DEMO_DIR/moneydevkit-core-local.tgz"

    - name: Build @moneydevkit/nextjs
      shell: bash
      run: npm run build --workspace packages/nextjs

    - name: Pack @moneydevkit/nextjs tarball
      shell: bash
      run: |
        DEMO_DIR="${{ inputs.demo-dir }}"
        rm -f "$DEMO_DIR/moneydevkit-nextjs-local.tgz"
        npm pack ./packages/nextjs --pack-destination "$DEMO_DIR"
        mv "$DEMO_DIR"/moneydevkit-nextjs-*.tgz "$DEMO_DIR/moneydevkit-nextjs-local.tgz"

    - name: Sync package-lock integrity for local tarballs
      shell: bash
      working-directory: ${{ inputs.demo-dir }}
      run: node ./scripts/sync-local-tarball.mjs

    - name: Install demo dependencies
      shell: bash
      working-directory: ${{ inputs.demo-dir }}
      run: npm ci
