name: Install Cypress system deps
description: Installs Xvfb and libraries needed by Cypress Electron on Ubuntu.
runs:
  using: composite
  steps:
    - name: Install Cypress dependencies (Xvfb)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libpango-1.0-0 \
          libcairo2 \
          libasound2t64 \
          libgtk-3-0 \
          libgtk2.0-0 \
          libxss1 \
          libxtst6 \
          libnotify-dev
